language: csharp
mono: none
dotnet: 3.1.300
solution: ./IdentityService/IdentityService.sln
script:
  - dotnet restore ./IdentityService/IdentityService.sln
  - dotnet build ./IdentityService/IdentityService.sln
  - dotnet test ./IdentityService/IdentityService.UnitTests.csproj;
jobs:
  include:
    - os: linux
      dotnet: 3.1.300
      mono: none
    - os: osx
      osx_image: xcode11
      dotnet: 3.1.300
      mono: none
      sudo: false # use the new container-based Travis infrastructure

# install:
#   - nuget restore IdentityService.sln
#   - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
# script:
#   - msbuild /p:Configuration=Release IdentityService.sln
#   - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./IdentityService.UnitTests/bin/Release/IdentityService.UnitTests.dll

