image: Visual Studio 2019

before_build:
  - dotnet restore ./IdentityService/IdentityService.sln
  - dotnet build ./IdentityService/IdentityService.sln
  - dotnet test ./IdentityService/IdentityService.UnitTests/IdentityService.UnitTests.csproj
  - choco install opencover.portable
  - choco install codecov

build:
  project: ./IdentityService/IdentityService.sln
  verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:test -filter:"+[UnitTestTargetProject*]* -[IdentityService*]*" -output:".\IdentityService_coverage.xml"
  - codecov -f "IdentityService_coverage.xml"
