# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  workingDirectory: './IdentityService'

steps:
- script: dotnet build --configuration $(workingDirectory) $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(workingDirectory)/IdentityService.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './IdentityService/IdentityService.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './IdentityService/IdentityService.UnitTests/IdentityService.UnitTests.csproj'
